In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from sqlalchemy import create_engine

In [4]:
df = pd.read_csv(r"C:\Users\dell\Downloads\archive\ncr_ride_bookings.csv") 
df.head(20)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI
5,2024-02-06,09:44:56,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,...,NaN,NaN,NaN,NaN,NaN,316.0,4.85,4.1,4.6,UPI
6,2024-06-17,15:45:58,"""CNR2002539""",Completed,"""CID6800553""",Go Mini,Vaishali,Punjabi Bagh,7.1,20.4,...,NaN,NaN,NaN,NaN,NaN,640.0,41.24,4.0,4.1,UPI
7,2024-03-19,17:37:37,"""CNR6568000""",Completed,"""CID8610436""",Auto,Mayur Vihar,Cyber Hub,12.1,16.5,...,NaN,NaN,NaN,NaN,NaN,136.0,6.56,4.4,4.2,UPI
8,2024-09-14,12:49:09,"""CNR4510807""",No Driver Found,"""CID7873618""",Go Sedan,Noida Sector 62,Noida Sector 18,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-12-16,19:06:48,"""CNR7721892""",Incomplete,"""CID5214275""",Auto,Rohini,Adarsh Nagar,6.1,26.0,...,NaN,NaN,NaN,1.0,Other Issue,135.0,10.36,NaN,NaN,Cash
10,2024-06-14,16:24:12,"""CNR9070334""",Completed,"""CID6680340""",Auto,Udyog Bhawan,Dwarka Sector 21,7.7,18.9,...,NaN,NaN,NaN,NaN,NaN,181.0,19.84,4.2,4.9,Cash
11,2024-09-18,08:09:38,"""CNR9551927""",No Driver Found,"""CID7568143""",Auto,Vidhan Sabha,AIIMS,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2024-06-25,22:44:15,"""CNR4386945""",Cancelled by Driver,"""CID5543520""",eBike,Patel Chowk,Kherki Daula Toll,4.6,NaN,...,NaN,1.0,Personal & Car related issues,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2024-09-11,19:29:39,"""CNR2987763""",Completed,"""CID2669710""",Go Mini,Malviya Nagar,Ghitorni Village,12.2,28.2,...,NaN,NaN,NaN,NaN,NaN,394.0,21.44,4.1,4.7,UPI
14,2024-10-18,18:28:53,"""CNR8962232""",Completed,"""CID1789354""",Go Mini,Madipur,GTB Nagar,14.0,30.9,...,NaN,NaN,NaN,NaN,NaN,836.0,39.55,4.7,4.4,UPI
15,2024-06-07,15:05:35,"""CNR2390352""",Completed,"""CID5432215""",Auto,Jama Masjid,Khan Market,8.5,36.9,...,NaN,NaN,NaN,NaN,NaN,410.0,34.76,4.0,4.9,Uber Wallet
16,2024-07-01,10:51:16,"""CNR3221338""",Completed,"""CID2581698""",Premier Sedan,IGI Airport,Madipur,5.6,27.5,...,NaN,NaN,NaN,NaN,NaN,401.0,21.97,4.9,4.3,UPI
17,2024-12-15,15:08:25,"""CNR6739317""",Cancelled by Driver,"""CID8682675""",Go Sedan,Vinobapuri,GTB Nagar,6.0,NaN,...,NaN,1.0,Customer related issue,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2024-11-24,09:07:10,"""CNR6126048""",Cancelled by Customer,"""CID1060329""",eBike,Kashmere Gate,Anand Vihar,12.4,NaN,...,Driver is not moving towards pickup location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2024-05-24,19:53:57,"""CNR9465840""",Cancelled by Driver,"""CID9046501""",eBike,Pitampura,Rajiv Nagar,10.3,NaN,...,NaN,1.0,Customer related issue,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.tail(20)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
149980,2024-12-10,15:31:45,"""CNR6231822""",No Driver Found,"""CID6232718""",Premier Sedan,Kirti Nagar,Sarojini Nagar,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149981,2024-12-10,09:46:40,"""CNR9611749""",Completed,"""CID1686695""",Go Sedan,Botanical Garden,IFFCO Chowk,5.8,18.5,...,NaN,NaN,NaN,NaN,NaN,91.0,43.43,4.9,4.1,UPI
149982,2024-11-13,06:51:19,"""CNR4448255""",No Driver Found,"""CID9138957""",Auto,Sikanderpur,Old Gurgaon,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149983,2024-03-23,20:33:36,"""CNR1937316""",Completed,"""CID7955264""",Go Mini,Gurgaon Railway Station,Azadpur,3.0,27.5,...,NaN,NaN,NaN,NaN,NaN,581.0,25.10,4.3,5.0,Credit Card
149984,2024-01-14,15:42:15,"""CNR2761999""",Incomplete,"""CID3743304""",Go Sedan,Azadpur,Lajpat Nagar,5.9,12.8,...,NaN,NaN,NaN,1.0,Customer Demand,1146.0,13.96,NaN,NaN,Cash
149985,2024-02-26,16:45:21,"""CNR2991975""",Completed,"""CID2480001""",Bike,AIIMS,Paharganj,13.4,27.0,...,NaN,NaN,NaN,NaN,NaN,193.0,13.29,4.2,4.6,Debit Card
149986,2024-03-15,17:49:46,"""CNR5247039""",Completed,"""CID6218492""",Premier Sedan,Preet Vihar,Anand Vihar ISBT,12.9,43.9,...,NaN,NaN,NaN,NaN,NaN,289.0,44.00,4.3,5.0,Cash
149987,2024-02-06,19:51:00,"""CNR1535042""",Completed,"""CID8787495""",Go Mini,Sushant Lok,Jama Masjid,2.3,19.9,...,NaN,NaN,NaN,NaN,NaN,101.0,10.69,4.2,4.5,UPI
149988,2024-08-17,10:43:13,"""CNR5410567""",Completed,"""CID6192221""",Bike,Udyog Bhawan,Lal Quila,13.4,26.6,...,NaN,NaN,NaN,NaN,NaN,96.0,27.72,4.3,4.2,UPI
149989,2024-07-22,10:04:18,"""CNR2531850""",Completed,"""CID7189367""",Auto,Shahdara,Panchsheel Park,14.2,22.8,...,NaN,NaN,NaN,NaN,NaN,75.0,8.33,4.2,4.9,Credit Card
149990,2024-09-26,12:31:22,"""CNR3212810""",Cancelled by Driver,"""CID6199171""",Auto,Kashmere Gate ISBT,GTB Nagar,10.7,NaN,...,NaN,1.0,Personal & Car related issues,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149991,2024-07-13,14:47:30,"""CNR5591053""",Completed,"""CID1829616""",Auto,Karol Bagh,Vishwavidyalaya,11.2,30.8,...,NaN,NaN,NaN,NaN,NaN,597.0,27.91,4.2,4.3,UPI
149992,2024-01-24,18:02:28,"""CNR1717894""",No Driver Found,"""CID9564749""",Go Mini,Nehru Place,Aya Nagar,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149993,2024-05-03,11:18:17,"""CNR9715958""",Completed,"""CID8835432""",Go Mini,Tughlakabad,Jama Masjid,13.2,20.1,...,NaN,NaN,NaN,NaN,NaN,280.0,29.89,4.1,4.7,Cash
149994,2024-06-14,16:46:53,"""CNR9572383""",Completed,"""CID2952237""",Go Mini,Akshardham,Greater Noida,8.2,30.6,...,NaN,NaN,NaN,NaN,NaN,388.0,10.51,4.3,4.9,UPI
149995,2024-11-11,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,...,NaN,NaN,NaN,NaN,NaN,475.0,40.08,3.7,4.1,Uber Wallet
149996,2024-11-24,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,...,NaN,NaN,NaN,NaN,NaN,1093.0,21.31,4.8,5.0,UPI
149997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,...,NaN,NaN,NaN,NaN,NaN,852.0,15.93,3.9,4.4,Cash
149998,2024-10-05,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,...,NaN,NaN,NaN,NaN,NaN,333.0,45.54,4.1,3.7,UPI
149999,2024-03-10,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,...,NaN,NaN,NaN,NaN,NaN,806.0,21.19,4.6,4.9,Credit Card

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   object
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   object
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    object
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

In [7]:
df.isnull().sum()

Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                              10500
Avg CTAT                              48000
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                        48000
dtype: int64

In [1]:
48000+57000+57000+48000+48000+141000+141000+123000+123000+139500+139500+48000+10500

1123500

In [8]:
10500/150000

0.07

In [9]:
48000/150000

0.32

In [10]:
df.columns=df.columns.str.lower() 
df.columns=df.columns.str.replace(' ','_')

In [11]:
obj_columns=df.dtypes[df.dtypes=="object"].index

In [12]:
obj_columns

Index(['date', 'time', 'booking_id', 'booking_status', 'customer_id',
       'vehicle_type', 'pickup_location', 'drop_location',
       'reason_for_cancelling_by_customer', 'driver_cancellation_reason',
       'incomplete_rides_reason', 'payment_method'],
      dtype='object')

In [13]:
num_columns=df.select_dtypes(include="number").columns

In [14]:
num_columns

Index(['avg_vtat', 'avg_ctat', 'cancelled_rides_by_customer',
       'cancelled_rides_by_driver', 'incomplete_rides', 'booking_value',
       'ride_distance', 'driver_ratings', 'customer_rating'],
      dtype='object')

In [15]:
df.columns

Index(['date', 'time', 'booking_id', 'booking_status', 'customer_id',
       'vehicle_type', 'pickup_location', 'drop_location', 'avg_vtat',
       'avg_ctat', 'cancelled_rides_by_customer',
       'reason_for_cancelling_by_customer', 'cancelled_rides_by_driver',
       'driver_cancellation_reason', 'incomplete_rides',
       'incomplete_rides_reason', 'booking_value', 'ride_distance',
       'driver_ratings', 'customer_rating', 'payment_method'],
      dtype='object')

In [16]:
df['booking_id'].value_counts()

booking_id
"CNR3648267"    3
"CNR9603232"    3
"CNR7642097"    3
"CNR7585544"    3
"CNR7908610"    3
               ..
"CNR3614535"    1
"CNR4499383"    1
"CNR9834201"    1
"CNR8779845"    1
"CNR6568000"    1
Name: count, Length: 148767, dtype: int64

In [17]:
df["customer_id"].value_counts()

customer_id
"CID6715450"    3
"CID4523979"    3
"CID6468528"    3
"CID7828101"    3
"CID8727691"    3
               ..
"CID5432215"    1
"CID2581698"    1
"CID8682675"    1
"CID1060329"    1
"CID9046501"    1
Name: count, Length: 148788, dtype: int64

In [18]:
df["vehicle_type"].unique()

array(['eBike', 'Go Sedan', 'Auto', 'Premier Sedan', 'Bike', 'Go Mini',
       'Uber XL'], dtype=object)

In [19]:
df["vehicle_type"].value_counts()

vehicle_type
Auto             37419
Go Mini          29806
Go Sedan         27141
Bike             22517
Premier Sedan    18111
eBike            10557
Uber XL           4449
Name: count, dtype: int64

In [20]:
df["vehicle_type"].isnull().sum()

np.int64(0)

In [21]:
df['booking_status'].unique()

array(['No Driver Found', 'Incomplete', 'Completed',
       'Cancelled by Driver', 'Cancelled by Customer'], dtype=object)

In [22]:
df['booking_status'].value_counts()

booking_status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

In [23]:
df['booking_status'].isnull().sum()

np.int64(0)

In [24]:
df['pickup_location'].value_counts()

pickup_location
Khandsa             949
Barakhamba Road     946
Saket               931
Badarpur            921
Pragati Maidan      920
                   ...
Mandi House         800
Noida Sector 18     799
Laxmi Nagar         797
Ashok Vihar         796
Ghitorni Village    790
Name: count, Length: 176, dtype: int64

In [25]:
df['drop_location'].value_counts()

drop_location
Ashram              936
Basai Dhankot       917
Lok Kalyan Marg     916
Narsinghpur         913
Cyber Hub           912
                   ...
MG Road             799
Bhiwadi             792
Shivaji Park        786
Anand Vihar ISBT    784
Huda City Centre    774
Name: count, Length: 176, dtype: int64

In [26]:
completed_avg_median_ctat= df[df["booking_status"]=="completed"]["avg_ctat"].median()
df.loc[df["booking_status"]=="completed","avg_ctat"]=df.loc[df["booking_status"]=="completed","avg_ctat"].fillna("completed_avg_median_ctat")

In [27]:
completed_avg_median_vtat= df[df["booking_status"]=="completed"]["avg_vtat"].median()
df.loc[df["booking_status"]=="completed","avg_vtat"]=df.loc[df["booking_status"]=="completed","avg_vtat"].fillna("completed_avg_median_vtat")

In [28]:
df["avg_vtat"].isnull().sum()

np.int64(10500)

In [29]:
df["avg_ctat"].isnull().sum()

np.int64(48000)

In [30]:
df["avg_ctat"]=df["avg_ctat"].fillna(0)

In [31]:
df["avg_vtat"]=df["avg_vtat"].fillna(0)

In [32]:
df[["avg_ctat","avg_vtat"]].head()

   avg_ctat  avg_vtat
0       0.0       0.0
1      14.0       4.9
2      25.8      13.4
3      28.5      13.1
4      19.6       5.3

In [33]:
df["date"]=pd.to_datetime(df["date"]).dt.date

In [34]:
df["date"].head()

0    2024-03-23
1    2024-11-29
2    2024-08-23
3    2024-10-21
4    2024-09-16
Name: date, dtype: object

In [35]:
df["time"]=pd.to_datetime(df["time"])

C:\Users\dell\AppData\Local\Temp\ipykernel_18580\329128545.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["time"]=pd.to_datetime(df["time"])

In [36]:
df["hour"]=pd.to_datetime(df["time"]).dt.hour

In [37]:
df.drop(columns=["time"],inplace=True)

In [38]:
df.columns

Index(['date', 'booking_id', 'booking_status', 'customer_id', 'vehicle_type',
       'pickup_location', 'drop_location', 'avg_vtat', 'avg_ctat',
       'cancelled_rides_by_customer', 'reason_for_cancelling_by_customer',
       'cancelled_rides_by_driver', 'driver_cancellation_reason',
       'incomplete_rides', 'incomplete_rides_reason', 'booking_value',
       'ride_distance', 'driver_ratings', 'customer_rating', 'payment_method',
       'hour'],
      dtype='object')

In [39]:
df["day"]=pd.to_datetime(df["date"]).dt.day

In [40]:
df["year"]=pd.to_datetime(df["date"]).dt.year

In [41]:
df["month"]=pd.to_datetime(df["date"]).dt.month

In [42]:
df.columns

Index(['date', 'booking_id', 'booking_status', 'customer_id', 'vehicle_type',
       'pickup_location', 'drop_location', 'avg_vtat', 'avg_ctat',
       'cancelled_rides_by_customer', 'reason_for_cancelling_by_customer',
       'cancelled_rides_by_driver', 'driver_cancellation_reason',
       'incomplete_rides', 'incomplete_rides_reason', 'booking_value',
       'ride_distance', 'driver_ratings', 'customer_rating', 'payment_method',
       'hour', 'day', 'year', 'month'],
      dtype='object')

In [43]:
df['cancelled_rides_by_customer'].value_counts()

cancelled_rides_by_customer
1.0    10500
Name: count, dtype: int64

In [44]:
df['cancelled_rides_by_customer']=df["cancelled_rides_by_customer"].fillna(0)

In [45]:
df['cancelled_rides_by_customer'].value_counts()

cancelled_rides_by_customer
0.0    139500
1.0     10500
Name: count, dtype: int64

In [46]:
df['reason_for_cancelling_by_customer'].value_counts()

reason_for_cancelling_by_customer
Wrong Address                                   2362
Change of plans                                 2353
Driver is not moving towards pickup location    2335
Driver asked to cancel                          2295
AC is not working                               1155
Name: count, dtype: int64

In [47]:
df['reason_for_cancelling_by_customer']=df['reason_for_cancelling_by_customer'].fillna("Not by customer")

In [48]:
df['reason_for_cancelling_by_customer'].value_counts()

reason_for_cancelling_by_customer
Not by customer                                 139500
Wrong Address                                     2362
Change of plans                                   2353
Driver is not moving towards pickup location      2335
Driver asked to cancel                            2295
AC is not working                                 1155
Name: count, dtype: int64

In [49]:
df['cancelled_rides_by_driver'].value_counts()

cancelled_rides_by_driver
1.0    27000
Name: count, dtype: int64

In [50]:
df['cancelled_rides_by_driver']=df['cancelled_rides_by_driver'].fillna(0)

In [51]:
df['cancelled_rides_by_driver'].value_counts()

cancelled_rides_by_driver
0.0    123000
1.0     27000
Name: count, dtype: int64

In [52]:
df["driver_cancellation_reason"].value_counts()

driver_cancellation_reason
Customer related issue                 6837
The customer was coughing/sick         6751
Personal & Car related issues          6726
More than permitted people in there    6686
Name: count, dtype: int64

In [53]:
df['driver_cancellation_reason']=df['driver_cancellation_reason'].fillna("Not cancelled by driver")

In [54]:
df["driver_cancellation_reason"].value_counts()

driver_cancellation_reason
Not cancelled by driver                123000
Customer related issue                   6837
The customer was coughing/sick           6751
Personal & Car related issues            6726
More than permitted people in there      6686
Name: count, dtype: int64

In [55]:
df['incomplete_rides'].value_counts()

incomplete_rides
1.0    9000
Name: count, dtype: int64

In [56]:
df['incomplete_rides'].isnull().sum()

np.int64(141000)

In [57]:
df['incomplete_rides']=df['incomplete_rides'].fillna(0)

In [58]:
df['incomplete_rides_reason'].value_counts()

incomplete_rides_reason
Customer Demand      3040
Vehicle Breakdown    3012
Other Issue          2948
Name: count, dtype: int64

In [59]:
df['incomplete_rides_reason']=df['incomplete_rides_reason'].fillna('Ride Completed')

In [60]:
df2=df

In [61]:
df2["booking_value"].isnull().sum()

np.int64(48000)

In [62]:
df2["booking_value"]=df2["booking_value"].fillna(0)

In [63]:
df2["ride_distance"].isnull().sum()

np.int64(48000)

In [64]:
df2["ride_distance"]=df2["ride_distance"].fillna(0)

In [65]:
df2['driver_ratings'].isnull().sum()

np.int64(57000)

In [66]:
df2['driver_ratings']=df2['driver_ratings'].fillna(df2["driver_ratings"].median())

In [67]:
df2['customer_rating'].isnull().sum()

np.int64(57000)

In [69]:
df2["customer_rating"]=df2["customer_rating"].fillna(df2["customer_rating"].median())

In [70]:
df2["cancelled_rides"]=df2["cancelled_rides_by_customer"]+df['cancelled_rides_by_driver']

In [71]:
df2["cancelled_rides"].value_counts()

cancelled_rides
0.0    112500
1.0     37500
Name: count, dtype: int64

In [72]:
df2["incomplete_rides"].value_counts()

incomplete_rides
0.0    141000
1.0      9000
Name: count, dtype: int64

In [73]:
df2['payment_method'].isnull().sum()

np.int64(48000)

In [74]:
df2['payment_method']=df2['payment_method'].fillna('Not Applicable')

In [75]:
valid_completion_rides= (
(df2["cancelled_rides_by_driver"] == 0) & # cancelled by Driver
(df2["cancelled_rides_by_customer"] == 0) & # cancelled by Customer
(df2['avg_vtat'] > 0) & #Driver actually spent time arriving
(df2['ride_distance'] > 0) #Passenger was actually transported
)

In [76]:
valid_completion_rides.sum()

np.int64(102000)

In [77]:
df2["payment_method"].isnull().sum()

np.int64(0)

In [78]:
engine = create_engine('mysql+pymysql://root:Viren%40015@localhost:3306/uber')

In [81]:
df2.to_sql(name='data',con=engine,if_exists="replace",index=False)

150000

In [83]:
df2.to_csv("cleaned_uber_data.csv",index=False)

In [84]:
df3=pd.read_csv("cleaned_uber_data.csv")

,date,booking_id,booking_status,customer_id,vehicle_type,pickup_location,drop_location,avg_vtat,avg_ctat,cancelled_rides_by_customer,...,booking_value,ride_distance,driver_ratings,customer_rating,payment_method,hour,day,year,month,cancelled_rides
0,2024-03-23,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,0.0,0.0,0.0,...,0.0,0.00,4.3,4.5,Not Applicable,12,23,2024,3,0.0
1,2024-11-29,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,0.0,...,237.0,5.73,4.3,4.5,UPI,18,29,2024,11,0.0
2,2024-08-23,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,0.0,...,627.0,13.58,4.9,4.9,Debit Card,8,23,2024,8,0.0
3,2024-10-21,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,0.0,...,416.0,34.02,4.6,5.0,UPI,17,21,2024,10,0.0
4,2024-09-16,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,0.0,...,737.0,48.21,4.1,4.3,UPI,22,16,2024,9,0.0